# Generated by Django 4.2.16 on 2024-11-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_mathang_giakhuyenmai'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathang',
            name='KhuyenMai',
            field=models.BooleanField(default=False),
        ),
    ]
