# Generated by Django 4.2.16 on 2024-11-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_mathang_khuyenmai'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='Email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='isCustomer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
