# Generated by Django 4.2.16 on 2024-11-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_khachhang_email_taikhoan_isadmin_taikhoan_iscustomer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathang',
            name='Gioitinh',
            field=models.CharField(choices=[('M', 'đực'), ('F', 'cái')], default='M', max_length=1),
        ),
    ]
