# Generated by Django 4.2.16 on 2024-11-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_mathang_gioitinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='HinhAnh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
